# Generated by Django 3.0.3 on 2020-06-30 21:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200630_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=tinymce.models.HTMLField(default='testing'),
            preserve_default=False,
        ),
    ]
