# Generated by Django 3.0.8 on 2020-08-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200730_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpeg', upload_to=''),
        ),
    ]
